# .github/workflows/graphops.yml
# Trigger this workflow with:
# gh workflow run --repo graphops/risingwave graphops.yml -f ref=graphops/uint256 -f tag=uint256
name: GraphOps - Build Container Image

on:
  workflow_dispatch:
    inputs:
      ref:                 # branch / tag / SHA to build
        description: "Git ref to build"
        required: true
        default: main
      image:               # optional full image name (registry/namespace/repo)
        description: "Image name (leave empty for ghcr.io/<owner>/<repo>)"
        required: false
        default: ""
      tag:                 # optional tag (leave empty for short SHA)
        description: "Image tag"
        required: false
        default: ""
      cargo_profile:       # CARGO_PROFILE for build optimization
        description: "Cargo profile (production, dev, etc.)"
        required: false
        default: "production"

jobs:
  build:
    runs-on: [self-hosted]
    permissions:              # needed for GHCR push with GITHUB_TOKEN
      contents: read
      packages: write

    steps:
      - name: Check out target ref
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive image name & tag
        id: meta
        run: |
          IMAGE="${{ inputs.image }}"
          if [ -z "$IMAGE" ]; then
            IMAGE="ghcr.io/${{ github.repository_owner }}/$(basename "${GITHUB_REPOSITORY}")"
          fi

          TAG="${{ inputs.tag }}"
          if [ -z "$TAG" ]; then
            TAG="$(echo "${GITHUB_SHA}" | cut -c1-8)"
          fi

          # Add architecture suffix like docker.sh
          ARCH="$(uname -m)"
          TAG_WITH_ARCH="${TAG}-${ARCH}"

          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "tag_with_arch=$TAG_WITH_ARCH" >> "$GITHUB_OUTPUT"
          echo "arch=$ARCH" >> "$GITHUB_OUTPUT"

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag_with_arch }}
          build-args: |
            GIT_SHA=${{ github.sha }}
            CARGO_PROFILE=${{ inputs.cargo_profile }}
          provenance: false     # disable SBOM/provenance to speed things up
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/risingwave-build-cache:${{ steps.meta.outputs.arch }}
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/risingwave-build-cache:${{ steps.meta.outputs.arch }},mode=max

      - name: Show built images
        run: |
          echo "--- docker images"
          docker images
